[package]
name = "project-code-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
tera = "1.17.1"
anyhow = "1.0.68"
thiserror = "1"
